"use strict"

module.exports = function (s) {
	return {
		xmin: s.xmin,
		xmax: s.xmax,
		yori: s.yori,
		width: s.width,
		ytouch: s.yori,
		touchwidth: s.width,
		belongRadical: s.belongRadical,

		hasGlyphStemAbove: s.hasGlyphStemAbove,
		hasSameRadicalStemAbove: s.hasSameRadicalStemAbove,
		hasRadicalPointAbove: s.hasRadicalPointAbove,
		radicalCenterRise: s.radicalCenterRise,
		hasGlyphPointAbove: s.hasGlyphPointAbove,
		glyphCenterRise: s.glyphCenterRise,
		hasRadicalLeftAdjacentPointAbove: s.hasRadicalLeftAdjacentPointAbove,
		hasRadicalRightAdjacentPointAbove: s.hasRadicalRightAdjacentPointAbove,
		radicalRightAdjacentRise: s.radicalRightAdjacentRise,
		radicalLeftAdjacentRise: s.radicalLeftAdjacentRise,
		hasGlyphLeftAdjacentPointAbove: s.hasGlyphLeftAdjacentPointAbove,
		hasGlyphRightAdjacentPointAbove: s.hasGlyphRightAdjacentPointAbove,
		glyphRightAdjacentRise: s.glyphRightAdjacentRise,
		glyphLeftAdjacentRise: s.glyphLeftAdjacentRise,
		hasRadicalLeftDistancedPointAbove: s.hasRadicalLeftDistancedPointAbove,
		hasRadicalRightDistancedPointAbove: s.hasRadicalRightDistancedPointAbove,
		radicalRightDistancedRise: s.radicalRightDistancedRise,
		radicalLeftDistancedRise: s.radicalLeftDistancedRise,
		hasGlyphLeftDistancedPointAbove: s.hasGlyphLeftDistancedPointAbove,
		hasGlyphRightDistancedPointAbove: s.hasGlyphRightDistancedPointAbove,
		glyphRightDistancedRise: s.glyphRightDistancedRise,
		glyphLeftDistancedRise: s.glyphLeftDistancedRise,

		hasGlyphStemBelow: s.hasGlyphStemBelow,
		hasSameRadicalStemBelow: s.hasSameRadicalStemBelow,
		hasRadicalPointBelow: s.hasRadicalPointBelow,
		radicalCenterDescent: s.radicalCenterDescent,
		hasGlyphPointBelow: s.hasGlyphPointBelow,
		glyphCenterDescent: s.glyphCenterDescent,
		hasRadicalLeftAdjacentPointBelow: s.hasRadicalLeftAdjacentPointBelow,
		hasRadicalRightAdjacentPointBelow: s.hasRadicalRightAdjacentPointBelow,
		radicalLeftAdjacentDescent: s.radicalLeftAdjacentDescent,
		radicalRightAdjacentDescent: s.radicalRightAdjacentDescent,
		hasGlyphLeftAdjacentPointBelow: s.hasGlyphLeftAdjacentPointBelow,
		hasGlyphRightAdjacentPointBelow: s.hasGlyphRightAdjacentPointBelow,
		glyphLeftAdjacentDescent: s.glyphLeftAdjacentDescent,
		glyphRightAdjacentDescent: s.glyphRightAdjacentDescent,
		hasRadicalLeftDistancedPointBelow: s.hasRadicalLeftDistancedPointBelow,
		hasRadicalRightDistancedPointBelow: s.hasRadicalRightDistancedPointBelow,
		radicalLeftDistancedDescent: s.radicalLeftDistancedDescent,
		radicalRightDistancedDescent: s.radicalRightDistancedDescent,
		hasGlyphLeftDistancedPointBelow: s.hasGlyphLeftDistancedPointBelow,
		hasGlyphRightDistancedPointBelow: s.hasGlyphRightDistancedPointBelow,
		glyphLeftDistancedDescent: s.glyphLeftDistancedDescent,
		glyphRightDistancedDescent: s.glyphRightDistancedDescent,

		hasGlyphFoldBelow: s.hasGlyphFoldBelow,
		hasRadicalFoldBelow: s.hasRadicalFoldBelow,
		hasGlyphSideFoldBelow: s.hasGlyphSideFoldBelow,
		hasRadicalSideFoldBelow: s.hasRadicalSideFoldBelow,
		hasGlyphVFoldBelow: s.hasGlyphVFoldBelow,
		hasRadicalVFoldBelow: s.hasRadicalVFoldBelow,

		posKey: { id: s.posKey.id, yori: s.posKey.yori },
		advKey: { id: s.advKey.id, yori: s.advKey.yori },
		posAlign: s.posAlign.map(function (x) { return x.id }),
		advAlign: s.advAlign.map(function (x) { return x.id }),
		posKeyAtTop: s.posKeyAtTop,
		slope: s.slope
	}
}
