"use strict";

module.exports = function(s) {
	return {
		xmin: s.xmin,
		xmax: s.xmax,
		y: s.y,
		width: s.width,
		belongRadical: s.belongRadical,

		hasGlyphStemAbove: !!s.hasGlyphStemAbove,
		hasSameRadicalStemAbove: !!s.hasSameRadicalStemAbove,
		hasRadicalPointAbove: !!s.hasRadicalPointAbove,
		radicalCenterRise: s.radicalCenterRise,
		hasGlyphPointAbove: !!s.hasGlyphPointAbove,
		glyphCenterRise: s.glyphCenterRise,
		hasRadicalLeftAdjacentPointAbove: !!s.hasRadicalLeftAdjacentPointAbove,
		hasRadicalRightAdjacentPointAbove: !!s.hasRadicalRightAdjacentPointAbove,
		radicalRightAdjacentRise: s.radicalRightAdjacentRise,
		radicalLeftAdjacentRise: s.radicalLeftAdjacentRise,
		hasGlyphLeftAdjacentPointAbove: !!s.hasGlyphLeftAdjacentPointAbove,
		hasGlyphRightAdjacentPointAbove: !!s.hasGlyphRightAdjacentPointAbove,
		glyphRightAdjacentRise: s.glyphRightAdjacentRise,
		glyphLeftAdjacentRise: s.glyphLeftAdjacentRise,
		hasRadicalLeftDistancedPointAbove: !!s.hasRadicalLeftDistancedPointAbove,
		hasRadicalRightDistancedPointAbove: !!s.hasRadicalRightDistancedPointAbove,
		radicalRightDistancedRise: s.radicalRightDistancedRise,
		radicalLeftDistancedRise: s.radicalLeftDistancedRise,
		hasGlyphLeftDistancedPointAbove: !!s.hasGlyphLeftDistancedPointAbove,
		hasGlyphRightDistancedPointAbove: !!s.hasGlyphRightDistancedPointAbove,
		glyphRightDistancedRise: s.glyphRightDistancedRise,
		glyphLeftDistancedRise: s.glyphLeftDistancedRise,

		hasGlyphStemBelow: !!s.hasGlyphStemBelow,
		hasSameRadicalStemBelow: !!s.hasSameRadicalStemBelow,
		hasRadicalPointBelow: !!s.hasRadicalPointBelow,
		radicalCenterDescent: s.radicalCenterDescent,
		hasGlyphPointBelow: !!s.hasGlyphPointBelow,
		glyphCenterDescent: s.glyphCenterDescent,
		hasRadicalLeftAdjacentPointBelow: !!s.hasRadicalLeftAdjacentPointBelow,
		hasRadicalRightAdjacentPointBelow: !!s.hasRadicalRightAdjacentPointBelow,
		radicalLeftAdjacentDescent: s.radicalLeftAdjacentDescent,
		radicalRightAdjacentDescent: s.radicalRightAdjacentDescent,
		hasGlyphLeftAdjacentPointBelow: !!s.hasGlyphLeftAdjacentPointBelow,
		hasGlyphRightAdjacentPointBelow: !!s.hasGlyphRightAdjacentPointBelow,
		glyphLeftAdjacentDescent: s.glyphLeftAdjacentDescent,
		glyphRightAdjacentDescent: s.glyphRightAdjacentDescent,
		hasRadicalLeftDistancedPointBelow: !!s.hasRadicalLeftDistancedPointBelow,
		hasRadicalRightDistancedPointBelow: !!s.hasRadicalRightDistancedPointBelow,
		radicalLeftDistancedDescent: s.radicalLeftDistancedDescent,
		radicalRightDistancedDescent: s.radicalRightDistancedDescent,
		hasGlyphLeftDistancedPointBelow: !!s.hasGlyphLeftDistancedPointBelow,
		hasGlyphRightDistancedPointBelow: !!s.hasGlyphRightDistancedPointBelow,
		glyphLeftDistancedDescent: s.glyphLeftDistancedDescent,
		glyphRightDistancedDescent: s.glyphRightDistancedDescent,

		hasGlyphFoldAbove: !!s.hasGlyphFoldAbove,
		hasRadicalFoldAbove: !!s.hasRadicalFoldAbove,
		hasGlyphSideFoldAbove: !!s.hasGlyphSideFoldAbove,
		hasRadicalSideFoldAbove: !!s.hasRadicalSideFoldAbove,

		hasGlyphFoldBelow: !!s.hasGlyphFoldBelow,
		hasRadicalFoldBelow: !!s.hasRadicalFoldBelow,
		hasGlyphSideFoldBelow: !!s.hasGlyphSideFoldBelow,
		hasRadicalSideFoldBelow: !!s.hasRadicalSideFoldBelow,
		hasGlyphVFoldBelow: !!s.hasGlyphVFoldBelow,
		hasRadicalVFoldBelow: !!s.hasRadicalVFoldBelow,

		hasEntireContourAbove: !!s.hasEntireContourAbove,
		hasEntireContourBelow: !!s.hasEntireContourBelow,

		posKey: { id: s.posKey.id, y: s.posKey.y, x: s.posKey.x },
		advKey: { id: s.advKey.id, y: s.advKey.y, x: s.advKey.x },
		posAlign: s.posAlign.map(z => ({ id: z.id, x: z.x, y: z.y })),
		advAlign: s.advAlign.map(z => ({ id: z.id, x: z.x, y: z.y })),
		diagHigh: !!s.diagHigh,
		diagLow: !!s.diagLow,
		posKeyAtTop: !!s.posKeyAtTop,
		rid: s.rid || 0,
		slope: s.slope,
		keyDX: s.advKey.x - s.posKey.x
	};
};
